### ISSUE TITLE
GetImage without transparency and black and white mode

### ISSUE THREAD

**Issue by z-dmitri** [GowenGit/docnet#11]
Thanks for the awesome library
It could be nice to have GetImage() method to retrieve bitmap array without transparency
And maybe black and white bitmap array option as well
There are many cases where transparency will take just additional memory - for example documents to OCR and etc
PDF mostly contains documents so it could be useful cases

**Comment by Modest-as** [comment]
Hey, thanks for the kind words. I am constantly looking for good new features to add while keeping the library very lightweight and fast and with no external dependencies. The latter especially requires some trade offs, by far the most confusing bit for the users is that library returns bitmap array instead of for example `jpeg` or `png` bytes that they can just save to a disk or something along these lines. All of that was done because I really do not want to add `System.Drawing` dependency to the core library which would add requirements to setup `GDI` dependencies on `linux` systems which is always annoying if you are running inside a container or just on bare metal. But I like this idea just adding some bitmap array post processors that you can optionally inject to format the output for transparency or greyscale might be useful to many. Will investigate more next time around I am working on some improvements.

**Comment by z-dmitri** [comment]
Thanks a lot
Keen to see transparency or greyscale options update
Have a great day

**Comment by Modest-as** [comment]
Hey, I have released a new version of docnet 2.0.0 with few breaking API changes. It also includes image transparency removal behavior, I decided against implementing greyscale support since that would modify the returning byte array from BGRA mode to something else thus it would be confusing for the users if the return type differs, but feel free to modify the returning image without transparency however you see fit
