### ISSUE TITLE
Create PDf from multiple bitmaps?

### ISSUE THREAD

**Issue by FatalSleep** [GowenGit/docnet#26]
I saw there's an example using JPEG, but is it possible to generate a PDF from a set of bitmaps as well?

**Comment by Modest-as** [comment]
hey why don't you convert your bitmap to jpeg first?

**Comment by FatalSleep** [comment]
Since converting from PDF -> Bitmap -> JPEG is slow. I think... there' may be a way to do PDF -> JPEG under the platform I'm using though: https://docs.microsoft.com/en-us/uwp/api/windows.data.pdf?view=winrt-19041

**Comment by Modest-as** [comment]
Converting pdf page to an image has to be done through bitmaps here since that is what pdfium supports. docnet tries to be platform and usage agnostic that is why it does not rely on system.drawing or similar namespaces. and does not try to convert the bitmap internally for you. You can achieve adequate performance taking the bitmap array and marshaling the bytes directly. The link above does rely on windows specific APIs so is not something we want to do here.
