### ISSUE TITLE
Arm/RaspberryPi support

### ISSUE THREAD

**Issue by ChristofferGreen** [GowenGit/docnet#48]
Hi!

Would there be any interest to also have an Arm/Linux/RaspberryPi target for this project? The use case we have is for handling pdf files in the self-hosted book viewer Kavita on a Raspberry Pi. If that would be acceptable I could look into submitting a pull request.

I suppose this would mostly be about compiling a 'docnet/src/Docnet.Core/runtimes/linux-arm/native/pdfium.so' binary and hooking it into the plumbing.

Thank you.

**Comment by Modest-as** [comment]
Hello, you are correct, the sole reason why we are not targeting ARM right now is because we do not have a pdfium binary compiled for that target. If that existed then just putting it in `docnet/src/Docnet.Core/runtimes/linux-arm/native/pdfium.so` should be sufficient. Pull requests are always welcome and thanks

**Comment by ChristofferGreen** [comment]
Great, thanks. Then I will look into building that binary.

**Comment by ChristofferGreen** [comment]
Hi, I added pull request for this.

**Comment by Modest-as** [comment]
Thanks again for the PR, binaries have been added to a `v2.4.0-alpha.1` nuget release
