### ISSUE TITLE
Add Arm/64-bit target binary

### ISSUE THREAD

**Issue by ChristofferGreen** [GowenGit/docnet#51]
Hi,

Recently we added a 32-bit arm target to docnet, this target has been working well in Kavita (self-hosted comic/book reader) since then, however, some of our users are running a 64-bit operating system on their raspberry pi and it looks like they are unable to use the 32-bit build.

I know there are issues with Travis credits but I wanted to ask how feasible it would be to add a 64-bit target. If it sounds ok I can see about submitting a pull request.

Thank you

**Comment by Modest-as** [comment]
Hey, this sounds reasonable so PRs are always welcome. If we include this, the nuget would also be released as alpha since I feel that the package will finally need to be split into the core nuget and additional nuget packages that carry platform specific binaries so people do not need to keep copying binaries that are not needed for their platforms.
