### ISSUE TITLE
Signed assembly (strong-named)

### ISSUE THREAD

**Issue by deankruger** [GowenGit/docnet#52]
Hi,
We would like to use docnet in a project that is strongly named (signed).

From the docs:
A strong-named assembly can only use types from other strong-named assemblies. Otherwise, the integrity of the strong-named assembly would be compromised.
https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named

Would it be possible to sign the assembly that is in the nuget package? All dotnet libraries usually come strongly named (signed) including the dotnet core ones.

**Comment by Modest-as** [comment]
Hi. Strong naming is a deprecated feature in .NET. new version of the runtime no longer validate the signatures so I feel like supporting it would bring no use to the project since the project does not maintain official support for .NET Framework. Also Microsoft advises against including this feature in 3rd party assemblies: https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

**Comment by edespong** [comment]
@mikkou-adafy The document you are referring to is not mentioning that is is a deprecated feature. 

Has the guideline changed since you closed this issue? I think it is quite clear in its recommendations:

"Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named."

Even more so in https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

"You should strong name your open-source .NET libraries. Strong naming an assembly ensures the most people can use it, and strict assembly loading only affects .NET Framework."

If the project does not maintain official support for .NET Framework then I think you should remove "Newer versions of .NET Framework are also supported" from the README.md
