### ISSUE TITLE
Apple M1 pdfium library support

### ISSUE THREAD

**Issue by mnerubashchenko** [GowenGit/docnet#82]
Hello, please add support for apple m1 new chips of pdfium library.

Thanks an advance

**Comment by benrb** [comment]
@Modest-as 

I've been needing this too and have added support [in a fork over here](https://github.com/GowenGit/docnet/compare/master...benrb:docnet:osx-arm64).

This works just fine when I include my build of docnet on x64 and arm64 macOS. The problem I have is getting the tests to run correctly on both platforms.

Please bear with me as I'm not fully up to speed on .net/MSBuild stuff.

I have edited `Docnet.Core.targets` to read:

```xml
<DocnetRuntime Condition=" '$(DocnetRuntime)' == '' AND '$([MSBuild]::IsOsPlatform(OSX))' AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'ARM64' ">osx-arm64</DocnetRuntime>
<DocnetRuntime Condition=" '$(DocnetRuntime)' == '' AND '$([MSBuild]::IsOsPlatform(OSX))' AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'x64'">osx-x64</DocnetRuntime>
<DocnetRuntime Condition=" '$(DocnetRuntime)' == '' AND '$([MSBuild]::IsOsPlatform(Linux))' ">linux</DocnetRuntime>
<DocnetRuntime Condition=" '$(DocnetRuntime)' == '' AND ('$(Prefer32Bit)' == 'true' OR '$(PlatformTarget)' == 'x86') AND '$([MSBuild]::IsOsPlatform(Windows))' ">win-x86</DocnetRuntime>
<DocnetRuntime Condition=" '$(DocnetRuntime)' == '' ">win-x64</DocnetRuntime>
```

Which will select the macOS runtime based on the architecture of the machine building a project. I did this because `$(PlatformTarget)` always returns an empty string and so can't be used to detect x64/arm64. It does allow the tests to run (and pass) on x64/arm64 macOS and doesn't break packaging up my web API which uses docnet.


My questions are:
- Is this be a valid approach? 
- If not, can you recommend an alternative? 
- If yes, would you be interested in accepting a pull request?

Thank you.

**Comment by benrb** [comment]
@axelgenus I'm happy to do so, but the [contributing guide](https://github.com/GowenGit/.github/blob/main/CONTRIBUTING.md) asks that changes are discussed in an issue first to check they are acceptable.

I'd prefer to give @Modest-as a chance to check they're happy with it before dropping a pull request on their toes :).

**Comment by jedidja** [comment]
Since @Modest-as hasn't responded to this thread in almost a month (the first @ ping), how much longer do we wait? :) Would really like to see your fix included @benrb!

**Comment by benrb** [comment]
The options are either wait, use a fork or find an alternative. A month isn't that long - we're not reimbursing the maintainer for their time here.

You're welcome to use the code I linked to, but I'm not looking to maintain a fork of this project and I'm not totally sure of the approach I took. There's also [PdfLibCore](https://github.com/jbaarssen/PdfLibCore) which may or may not be a viable alternative.

**Comment by li7vinov-denis** [comment]
@mnerubashchenko
I've found another solution - you can add extra nuget package to your project.
It's worked for me
https://github.com/bblanchon/pdfium-binaries

**Comment by Modest-as** [comment]
Hey, PR here is definitely welcome since I do not have an m1 to test things on. This would be an interim solution since I consider moving core of this library to wasm.

**Comment by barnettben** [comment]
@Modest-as Thank you. I have opened a pull request: #86.

**Comment by jedidja** [comment]
> The options are either wait, use a fork or find an alternative. A month isn't that long - we're not reimbursing the maintainer for their time here.

Yep, you're absolutely right. I did not mean to sound that I didn't appreciate what @Modest-as has done. Apologies for that.

> You're welcome to use the code I linked to, but I'm not looking to maintain a fork of this project and I'm not totally sure of the approach I took. There's also [PdfLibCore](https://github.com/jbaarssen/PdfLibCore) which may or may not be a viable alternative.
> 
> That said, I like this library so hope it keeps going!

Agreed!

**Comment by barnettben** [comment]
@jedidja I think I might have come off a bit brusque, that wasn't my intention and no need for apologies!

**Comment by Modest-as** [comment]
cheers boys, `2.5.0-alpha.1` is pushed to nuget now, give it a spin.
